services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reactjs
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local