services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reactjs
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local